name: grocery_admin_panel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICONS
  iconsax: ^0.0.8

  # STATE MANAGEMENT
  get: ^4.6.6

  # LOCAL STORAGE
  get_storage: ^2.1.1

  # FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.7.3
  cloud_firestore: ^4.17.1

  # UTILITY
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.8
  lottie: ^2.7.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/animations/

  fonts:
    - family: Cal
      fonts:
        - asset: assets/fonts/Cal.otf
